---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: report-time-range  
  - name: orgs-usage
outputs:
  - name: orgs-usage-consolidated

run:
  path: sh
  args:
  - -exc
  - |
    node ./pipeline-scripts/scripts/consolidate-usage-data.js ./orgs-usage/pcf-orgs-usage.json ./orgs-usage-consolidated/pcf-usage-consolidated.json
    find .

# params:
#   PCF_API_ENDPOINT:
#   PCF_APPS_DOMAIN:
#   SYS_ADMIN_USER:
#   SYS_ADMIN_PASSWORD:
