---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: orgs-usage
outputs:
  - name: orgs-usage-consolidated

run:
  path: pipeline-scripts/scripts/consolidate-usage-data.sh

# params:
#   PCF_API_ENDPOINT:
#   PCF_APPS_DOMAIN:
#   SYS_ADMIN_USER:
#   SYS_ADMIN_PASSWORD:
