---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: report-time-range
  - name: orgs-usage-consolidated

run:
  path: sh
  args:
  - -exc
  - |
    npm install nodemailer
    node pipeline-scripts/scripts/email-usage-file.js

# params:
#   SMTP_HOST:
#   SMTP_PORT:
#   SMTP_USERNAME:
#   SMTP_PASSWORD:
#   EMAIL_FROM:
#   EMAIL_TO:
