---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
outputs:
  - name: outputdir

run:
  path: pipeline-scripts/scripts/get-all-orgs.sh
