---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
outputs:
  - name: orgs-list

run:
  path: pipeline-scripts/scripts/get-orgs-and-quotas.sh
