---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pcf-usage-tools
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: orgs-list
outputs:
  - name: spaces-usage

run:
  path: pipeline-scripts/scripts/get-apps-usage.sh
