---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/concourse-send-email
    tag: "latest"

inputs:
  - name: pipeline-scripts
  - name: email-text

run:
  path: sh
  args:
  - -exc
  - |
    mv /app/node_modules .
    node pipeline-scripts/scripts/send-email.js

# params:
#   SMTP_HOST:
#   SMTP_PORT:
#   SMTP_USERNAME:
#   SMTP_PASSWORD:
#   EMAIL_FROM:
#   EMAIL_TO:
#   EMAIL_SUBJECT_FILE: ./email-text/email-text-success.txt
#   EMAIL_TEXT_FILE: ./email-text/email-text-success.txt
