---
resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-test

resources:
- name: pipeline-scripts
  type: git
  source:
    branch: master
    uri: {{git-project-url}}
- name: file-repository
  type: s3
  source:
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    regexp: {{s3-directory-path}}
    region_name: us-west-1
- name: monthly-trigger
  type: cron-resource
  source:
    location: "America/New_York"
    expression: "0 6 1 * *"
    # trigger on the first day of each month at 6:00am ET

jobs:
- name: retrieve-and-process-pcf-usage-data
  serial: true
  public: true
  plan:
  - get: pipeline-scripts
    trigger: false
  # - get: file-repository
  # - get: monthly-trigger
  #   trigger: true
  - task: define-report-time-range
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pivotalservices/pcf-usage-tools
          tag: "latest"
      outputs:
        - name: report-time-range
      run:
        path: sh
        args:
        - -exc
        - |
          #
          # Sample 1: set time range as last month's start and end dates
          #
          # date1=$(date --date="-1 month" +"%Y-%m-01")
          # date -d "$(date +%Y-%m-01) -1 day" +"{ 'USAGE_START_DATE':'$date1', 'USAGE_END_DATE':'%Y-%m-%d' }" > ./report-time-range/report-time-range.json
          #
          # Sample 2: set time range as current month's start to current date
          #
          date1=$(date -d "$(date +%Y-%m-01)" +"%Y-%m-01")
          date -d "$(date +%Y-%m-%d)" +"{ 'USAGE_START_DATE':'$date1', 'USAGE_END_DATE':'%Y-%m-%d' }" > ./report-time-range/report-time-range.json
          #
          sed -i "s/[']/\"/g" ./report-time-range/report-time-range.json
          cat  ./report-time-range/report-time-range.json

  - task: get-usage-data
    file: pipeline-scripts/ci/tasks/get-usage-data.yml
    params:
      PCF_API_ENDPOINT: {{pcf-api-endpoint}}
      PCF_APPS_DOMAIN: {{pcf-apps-domain}}
      SYS_ADMIN_USER: {{pcf-sys-admin-user}}
      SYS_ADMIN_PASSWORD: {{pcf-sys-admin-user-password}}

  - task: consolidate-usage-data
    file: pipeline-scripts/ci/tasks/consolidate-usage-data.yml
    params:
      PCF_DEPLOY_NAME: {{pcf-deploy-name}}

  - put: file-repository
    params:
      file: ./orgs-usage-consolidated/*.json
      acl: public-read

  # - task: email-usage-file
  #   file: pipeline-scripts/ci/tasks/email-usage-file.yml
  #   params:
  #     PCF_DEPLOY_NAME: {{pcf-deploy-name}}
  #     SMTP_HOST: {{smtp-host}}
  #     SMTP_PORT: {{smtp-port}}
  #     SMTP_USERNAME: {{smtp-username}}
  #     SMTP_PASSWORD: {{smtp-password}}
  #     EMAIL_FROM: {{email-from}}
  #     EMAIL_TO: {{email-to}}

# - name: backup-elastic-runtime
#   serial: true
#   public: true
#   plan:
#   - get: pcf-backup-scripts
#     trigger: false
#   - get: trigger-daily-after-1am
#     trigger: true
#     passed:
#       - backup-opsman
#   - task: backup-elastic-runtime
#     file: pcf-backup-scripts/pcf-cfops-backup/ci/tasks/cfops_backup.yml
